robot_config:
  tcp_link_name: "right_gripper"    # defines the pose of the tool center point
  base_link_name: "panda_link0"     # the link that defines the base pose
  # eef_base_link_name: "panda_hand"  # the link that defines the end effector pose
  eef_links: ["panda_link8", "panda_hand", "panda_grasptarget", "right_gripper", "panda_leftfinger", "panda_rightfinger"]
  eef_visual_links: ["panda_hand", "panda_leftfinger", "panda_rightfinger"]
  arm_visual_links: ["panda_link0", "panda_link1", "panda_link2", "panda_link3", "panda_link4", "panda_link5", "panda_link6", "panda_link7", "panda_hand", "panda_leftfinger", "panda_rightfinger"]
  arm_links: ["panda_link0", "panda_link1", "panda_link2", "panda_link3", "panda_link4", "panda_link5", "panda_link6", "panda_link7", "panda_link8", "panda_hand", "panda_grasptarget", "right_gripper", "panda_leftfinger", "panda_rightfinger"]
  auxiliary_joint_names: ["panda_finger_joint1", "panda_finger_joint2"]  # not controlled by neural network
  auxiliary_joints_values: [0.04, 0.04] # default values of auxiliary joints
  neutral_config: [-0.017792060227770554, -0.7601235411041661, 0.019782607023391807, -2.342050140544315, 0.029840531355804868, 1.5411935298621688, 0.7534486589746342] # in order of how non-auxiliary joints are defined in urdf